export const IPC_EVENTS = {
  CHANGE_BADGE_COUNT: 'CHANGE_BADGE_COUNT',
  CHANGE_TRAY: 'CHANGE_TRAY',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
  MINIMIZE_WINDOW: 'MINIMIZE_WINDOW',
  OPEN_WINDOW: 'OPEN_WINDOW',
};
